config/routes.rb
Rails.application.routes.draw do
  
  resources :api_keys, only: [:index, :create, :destroy]
  
  devise_for :users
  
  namespace :api do
    namespace :v1 do
      get '/book', to: 'book#index'
      get '/author', to: 'author#index'
      get '/publisher', to: 'publisher#index'
      get '/category', to: 'category#index'
      get '/search', to: 'search#index'      
    end
  end

  root to: 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="splash-container">
  <div class="splash">
    <h1 class="splash-head">Bookshark</h1>
    <p class="splash-subhead">
      A book metadata api service for greek national bibliography, powered by biblionet.gr
    </p>
    <p>     
      <%= link_to "Documentation", "http://docs.bookshark.bibliography.gr", target: "_blank", class: "pure-button pure-button-primary" %>               
      <%= link_to "Get a Developer API Key", api_keys_path, class: "pure-button pure-button-primary" %>      
    </p>
  </div>
</div>
<div class="content-wrapper-under-splash">
  <div class="content">
    <h2 onclick="scrollToBottom()" class="content-head is-center">Learn More</h2>
    <div class="pure-g">
      <div class="l-box pure-u-1 pure-u-md-1-3">
        <h3 class="content-subhead">Over 200.000 books.</h3>
        <p>
          Bookshark is a book metadata provider based on <a href="http://biblionet.gr/">biblionet's</a> database which contains over 200000 books from 7000 authors.
        </p>
      </div>
      <div class="l-box pure-u-1 pure-u-md-1-3">
        <h3 class="content-subhead">JSON responses.</h3>
        <p>
          Metadata responses are in json format inspired by <a href="http://okfnlabs.org/bibjson/">bibjson</a> for easy parsing and process.
        </p>
      </div>
      <div class="l-box pure-u-1 pure-u-md-1-3">
        <h3 class="content-subhead">Simple HTTP API.</h3>
        <p>
          All requests are done through http. Get a single book or perform complex searches just by configuring the url.
        </p>
      </div>
    </div>
  </div>
</div>